### ISSUE TITLE
[BUG] NET and CPU graph overwriting small box

### ISSUE THREAD

**Issue by danbulant** [aristocratos/bashtop#14] opened 2020-04-23 10:58 UTC
**Describe the bug**
While running bashtop, the small CPU infobox is being overwritten by the main graph

**Expected behavior**
To work as in screenshots from readme

**Screenshots**
![image](https://user-images.githubusercontent.com/30036876/80091724-d9c35300-8561-11ea-9e7d-edda9987ae3e.png)

**Info (please complete the following information):**
 - Linux distribution and version - Debian buster
 - System locale (output of "echo $LANG") - en_US.UTF-8
 - Bash version - bash 5.0 (x86_64-debian-linux-gnu)

**Additional context**
$HOME/.config/bashtop/error.log":
```
 
New instance of bashtop version: 0.8.3 Pid: 6266
```

**Comment by aristocratos** [comment] 2020-04-23 14:59
> Bash version - zsh 5.7.1 (x86_64-debian-linux-gnu)

Need bash version, not zsh version.

**Comment by aristocratos** [comment] 2020-04-26 10:17
Closing until further info is provided.

**Comment by danbulant** [comment] 2020-04-26 10:36
Is bash version applicable when I'm not using it?

**Comment by aristocratos** [comment] 2020-04-26 10:59
As is hinted in the name "BASHtop" and is listed under dependencies. Bashtop needs bash version 4.4 or later to run. No matter which shell you use yourself bash gets called by the script on the first line. If you haven't got bash installed and try to run bashtop with zsh, there will be problems since there is a lot of differences in how zsh and bash interpret a script.

**Comment by danbulant** [comment] 2020-04-29 08:15
Oh, sorry, didn't know that.

I have bash 5.0
```
GNU bash, version 5.0.3(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by danbulant** [comment] 2020-05-06 07:22
Same bug applies to `net` usage as well

**Comment by danbulant** [comment] 2020-05-06 07:24
I also tried running it from `bash` instead of zsh, same result.

Another information that might help is that it doesn't start directly from the right, instead it starts from the correct place but each rerender starts a bit more to the right. The graph doesn't overwrite text, it shows under the text box.

**Comment by aristocratos** [comment] 2020-05-06 13:57
Do you meet the standards of the [compatibility notice](https://github.com/aristocratos/bashtop#compatibility)?

Also what terminal are you using?

**Comment by danbulant** [comment] 2020-05-07 12:44
I'm using Konsole which should meet the compatibility notice

**Comment by aristocratos** [comment] 2020-05-07 14:41
Also depends on font compatibility. Can you post a screenshot of the complete window.

**Comment by danbulant** [comment] 2020-05-07 19:30
Fonts shouldn't be an issue, powerline fonts worked out of the box.
![image](https://user-images.githubusercontent.com/30036876/81336642-fa36f580-90a9-11ea-84c8-481803823dc7.png)

**Comment by aristocratos** [comment] 2020-05-07 19:33
Have you tried different fonts?

Since the problem seems to be that the different braille symbols that make up the graphs are rendered at different widths, which they shouldn't do.

**Comment by danbulant** [comment] 2020-05-07 19:40
Tried few different mono-spaced fonts in bashtop, still same issue

**Comment by aristocratos** [comment] 2020-05-07 19:47
Have you tried in a different terminal?

**Comment by aristocratos** [comment] 2020-05-07 19:59
This is very likely a issue with konsole, either a setting or something with your version of konsole. The graph symbols shouldn't be able to render behind the text in the cpu box. It's essentially showing two different characters in the same space in your screenshot.

**Comment by danbulant** [comment] 2020-05-07 19:59
Wow.
Tried xterm and worked just fine...
It's weird, because xterm has no support for powerline, so I don't see the font correctly in zsh (I'm using a theme which uses powerline)...

**Comment by aristocratos** [comment] 2020-05-07 20:01
You could try updating konsole if not on latest version, or look through all the settings if something is messing with unicode character width.

**Comment by aristocratos** [comment] 2020-05-07 20:03
Closing this since the issue is caused by konsole.
Make a bug report with kde.org if it persists.

**Closed by aristocratos** 2020-05-07 20:03 UTC
Labels: question

**Comment by danbulant** [comment] 2020-05-07 20:10
Sure, thanks
