### ISSUE TITLE
[REQUEST] GPU stats

### ISSUE THREAD

**Issue by reisraff** [aristocratos/bashtop#99] opened 2020-05-04 16:12 UTC
**Describe the solution you'd like**
Would be awesome a new section for GPU stats usage, like CACHE memory, idle timing... etc.

**Describe alternatives you've considered**
Over all we can apply it for the main graphics vendors that is Nvidia, AMD, etc.

**Comment by aristocratos** [comment] 2020-05-04 17:51
Duplicate of #26

**Closed by aristocratos** 2020-05-04 17:51 UTC
Labels: duplicate
