### ISSUE TITLE
[BUG] Per core/process load graph overflows

### ISSUE THREAD

**Issue by danielroek** [aristocratos/bashtop#158] opened 2020-07-02 13:11 UTC
**Describe the bug**
Text overflows on per core and per process load monitor

**To Reproduce**

[Steps to reproduce the behavior:]

**Expected behavior**

[A clear and concise description of what you expected to happen.]

**Screenshots**

![image](https://user-images.githubusercontent.com/32639467/86361939-d55b9a80-bc74-11ea-8150-77ba668a46d0.png)

**Info (please complete the following information):**
 - Bashtop version: 0.9.12
 - (Linux) Linux distribution and version: Archlinux
 - (Linux) Data collection type (/proc or psutil): proc
 - (OSX/FreeBSD) Os release version:
 - Terminal used: ssh via Konsole an Yakuke on Manjaro
 - Font used: No clue, never changed it
 - Bash version, "bash --version" (version 4.4 or above is required): 5.0.17(1)-release
 - Locales: output of "locale -v"

**Additional context**

contents of `$HOME/.config/bashtop/error.log`
$ cat error.log 
 
New instance of bashtop version: 0.9.1 Pid: 635
New instance of bashtop version: 0.9.1 Pid: 1038
New instance of bashtop version: 0.9.1 Pid: 1189
New instance of bashtop version: 0.9.1 Pid: 209494
New instance of bashtop version: 0.9.1 Pid: 213124
New instance of bashtop version: 0.9.12 Pid: 1112610
New instance of bashtop version: 0.9.12 Pid: 1116318
New instance of bashtop version: 0.9.12 Pid: 1117977
New instance of bashtop version: 0.9.12 Pid: 1131265
New instance of bashtop version: 0.9.12 Pid: 1132864
New instance of bashtop version: 0.9.12 Pid: 1132864
New instance of bashtop version: 0.9.12 Pid: 1137209
New instance of bashtop version: 0.9.12 Pid: 1138956

(enable error-logging in "$HOME/.config/bashtop/bashtop.cfg" if missing)

**Comment by aristocratos** [comment] 2020-07-02 13:15
Duplicate of #83

**Closed by aristocratos** 2020-07-02 13:15 UTC
Labels: bug
