### ISSUE TITLE
[BUG] updating will freeze

### ISSUE THREAD

**Issue by magesticmage** [aristocratos/bashtop#84] opened 2020-05-02 03:28 UTC
**Describe the bug**

After a few minutes, sometimes more, sometimes less, screen updates stop and or pause until a key is pressed such as space-bar.

**To Reproduce**

[Steps to reproduce the behavior:]

**Expected behavior**

[A clear and concise description of what you expected to happen.]

**Screenshots**

[If applicable, add screenshots to help explain your problem.]

**Info (please complete the following information):**
 - Bashtop version: 0.8.20
 - Linux distribution and version: Linux Mint 19.3 XFCE
 - Terminal used: xfce4-terminal 0.8.7.4
 - Font used: Terminal Font: Monospace 10 
 - Bash version, "bash --version" (version 4.4 or above is required): 4.4.20 
 - Locales: output of "locale -v" 

LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

**Additional context**

contents of `$HOME/.config/bashtop/error.log`

New instance of bashtop version: 0.8.17 Pid: 10767
 
New instance of bashtop version: 0.8.17 Pid: 430
 
New instance of bashtop version: 0.8.18 Pid: 20784
 
New instance of bashtop version: 0.8.18 Pid: 24284
 
New instance of bashtop version: 0.8.20 Pid: 31575
 
New instance of bashtop version: 0.8.20 Pid: 27024
 
New instance of bashtop version: 0.8.20 Pid: 29816
(enable error-logging in "$HOME/.config/bashtop/bashtop.cfg" if missing)

**Comment by magesticmage** [comment] 2020-05-02 03:44
the clock even stops

**Comment by aristocratos** [comment] 2020-05-02 08:51
What's your "Update ms" and "Proc sorting" variables set to in the options?
Could you also post a screenshot of what it looks like when frozen?

**Comment by drazil100** [comment] 2020-05-02 09:20
I have been having this issue too. If I just leave it open in the background it will sometimes just freeze until I push buttons.

> What's your "Update ms" and "Proc sorting" variables set to in the options?
> Could you also post a screenshot of what it looks like when frozen?

For me I keep proc sorting and update ms at default. It doesn't look any different when frozen than unfrozen. It just stops updating the screen. Also upon unfreezing it the graphs appends new data to what was in the graph when it froze rather than replacing the data with up to date data indicating it probably isn't actually monitoring your system in the background while frozen. (though this is an assumption I am making having not looked at your code)

Btw @magesticmage you should consider changing the title. "[BUG]" doesn't offer any information on what the issue is about.

**Comment by drazil100** [comment] 2020-05-02 09:29
Oh hey while typing the above message I left it open in the background in hopes it would freeze and it did.

Here is a screenshot of it frozen.
![Screenshot from 2020-05-02 04-24-35](https://user-images.githubusercontent.com/17794391/80860427-29beab80-8c2d-11ea-9ded-be3595a802b1.png)

Here is a screenshot directly after unfreezing it
![Screenshot from 2020-05-02 04-24-53](https://user-images.githubusercontent.com/17794391/80860456-4e1a8800-8c2d-11ea-8f45-d5cc64da680a.png)

As you can see the graph data remains the same aside from the new additions on the end however the time on the clock jumps ahead 3 minutes.

**Comment by aristocratos** [comment] 2020-05-02 09:32
Are you using a bash version lower than 5 too?
Could be a issue with "date" command.
Would you mind posting the output of 
``` bash
date +%s%3N
```

**Comment by drazil100** [comment] 2020-05-02 09:37
austin@VivoBook:~$ bash --version
GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

austin@VivoBook:~$ date +%s%3N
1588412050953

Also I am on Linux Mint 19.3 Tricia Cinnamon Edition

Any further information I can provide im more than happy to.

**Comment by drazil100** [comment] 2020-05-02 09:57
Also to clarify in case I was misunderstood. When I said "The clock jumps ahead 3 minutes" I mean I waited 3 minutes after it froze to unfreeze it to show that the graphs really were frozen. Not that unfreezing it did anything funky to the displayed time.

**Comment by aristocratos** [comment] 2020-05-02 10:11
Would you mind testing this test version and see if it helps:
https://gist.github.com/aristocratos/70b0c301735e45a1038f45b213ca7600

**Comment by drazil100** [comment] 2020-05-02 10:18
Sure thing! I will test first thing when I get up tomorrow so I can leave it running for an extended period of time.

**Comment by aristocratos** [comment] 2020-05-02 10:28
Great :)
Gonna set up a vm of Linux Mint 19.3 and run tests, and if it's not fixed I should hopefully be able to reproduce the error and get some more information.

**Comment by aristocratos** [comment] 2020-05-02 11:01
Pushed the possible fix and a fix for iostat in v0.8.21
So download that version instead.

**Comment by Generator** [comment] 2020-05-02 14:41
I confirm that, that happens when using bashtop over SSH, on local machine that only happen on previous versions (<=0.8.16)

![Captura de ecrã_2020-05-02_15-37-00](https://user-images.githubusercontent.com/44146/80867252-3376fc00-8c8b-11ea-897a-3ee5fee79656.png)

**Comment by drazil100** [comment] 2020-05-02 18:45
Still freezes on v0.8.21

**Comment by aristocratos** [comment] 2020-05-02 18:54
Haven't been able to replicate the issue yet. It sounds like you are getting stuck in a loop somewhere in the script, but I put in fail safes for the most probable ones in v0.8.21.

Would you mind sharing some more info, like system specs and possibly if you got any resource hungry applications running at the same time?

It's also possible the bug is related to fact that both of you are running bash version 4.4.20.
@Generator are you also using bash 4.4.20?

**Comment by drazil100** [comment] 2020-05-02 18:59
Doing some further testing. Had it freeze on me in 5 minutes and 46 seconds after opening it.

As for specs I have an intel celeron N4000 with 4GB of ram.

**Comment by aristocratos** [comment] 2020-05-02 19:04
Would you mind running `bashtop --debug` but only for a second or so, the log file it creates gets crazy big if it's kept running. And then mailing or sharing the resulting `$HOME/.config/bashtop/tracing.log`

**Comment by drazil100** [comment] 2020-05-02 19:08
Here you go.
[tracing.log](https://github.com/aristocratos/bashtop/files/4568601/tracing.log)

**Comment by aristocratos** [comment] 2020-05-02 19:15
How often does it freeze on start? Was thinking if you could try restarting a couple of times with debug flag and if it freezes at start, quit and send that tracing.log
Then I would likely be able to see what it's getting stuck at.

**Comment by aristocratos** [comment] 2020-05-02 19:20
Or depending on your disk space, run it until it freezes, quit and then `tail -n 10000 tracing.log > trimmed-tracing.log`

**Comment by drazil100** [comment] 2020-05-02 19:21
It has yet to freeze on start for me. That said assuming I can get it to freeze on my other machine that has more disk space I wouldn't mind generating a much larger debug file. If there was also a way to record the time it displays at the top in the debug each screen refresh we could search for the exact point it freezes.

**Comment by aristocratos** [comment] 2020-05-02 19:24
Should be able to find it by looking at any big chunks lacking any `echo` commands.

**Comment by drazil100** [comment] 2020-05-02 19:31
I don't know that ill be able to actively catch it freeze within a reasonable number of write cycles after it freezes. It kinda happens randomly. Sometimes quickly sometimes not so quickly. Would the last 10000 lines be useful if I am a couple minutes late?

Ill debug it after I eat.

**Comment by aristocratos** [comment] 2020-05-02 19:34
If it's still frozen when you quit out it should be good, since the error would be repeating.

**Comment by Generator** [comment] 2020-05-02 20:16
> @Generator are you also using bash 4.4.20?

Raspbian:
```
$ bash --version
GNU bash, version 5.0.3(1)-release (arm-unknown-linux-gnueabihf)
```
Archlinux:
```
$ bash --version                                              
GNU bash, versão 5.0.16(1)-release (x86_64-pc-linux-gnu)
```

It freezes after some minutes randomly only on SSH

**Comment by drazil100** [comment] 2020-05-02 20:18
I left it running on my other machine in the foreground while cooked lunch about an hour ago and it didn't freeze. I am gonna try backgrounding the window and seeing if that has anything to do with it cause I have never had it freeze while I was looking at it.

**Comment by aristocratos** [comment] 2020-05-02 20:50
My "Linux Mint 19.3" vm frooze while testing, but the os itself not bashtop. Came across this:
https://forums.linuxmint.com/viewtopic.php?t=309961
And this:
https://forums.linuxmint.com/viewtopic.php?p=1739927
Are you sure only bashtop freezes, or other programs as well?

**Comment by drazil100** [comment] 2020-05-02 20:54
when it freezes for me I only notice bashtop freezing. Also I can easily resume. Right now im trying to get it to freeze again to get the logs. Any particular way you want me to stop bashtop when it does freeze to get the best logs and not risk resuming it?

**Comment by aristocratos** [comment] 2020-05-02 20:56
Preferably a `kill -s 9 "pid"`, then the problems should right at the end of the log.

**Comment by drazil100** [comment] 2020-05-02 21:28
FINALLY. 
[trimmed-tracing.log](https://github.com/aristocratos/bashtop/files/4568973/trimmed-tracing.log)

Backed up the full log. If you need more let me know.

**Comment by aristocratos** [comment] 2020-05-02 21:40
Can you upload a bigger chunk, like 50k lines instead, everything in the last log looks completely normal and there's even echo commands, which would update the screen unless echo is broken which seems unlikely.

**Comment by drazil100** [comment] 2020-05-02 21:42
[trimmed-tracing.log](https://github.com/aristocratos/bashtop/files/4569029/trimmed-tracing.log)
Here is double that

**Comment by aristocratos** [comment] 2020-05-02 21:43
The last line is `read -rsd '' -t 0.001 -n 1 key` which should time out in 1 millisecond.
The last time string was 04:23:42 PM do you remember what was showing when it froze?

**Comment by drazil100** [comment] 2020-05-02 21:45
I think thats what time it froze actually. I should have taken a screenshot. The 42 at the end sounds very familiar.

**Comment by aristocratos** [comment] 2020-05-02 21:46
And the time is consistent second to second, with echo commands in between. How big is the complete log?

**Comment by drazil100** [comment] 2020-05-02 21:47
174.7 MB

**Comment by aristocratos** [comment] 2020-05-02 21:48
Ok, should be ok size if you bzip it?

**Comment by drazil100** [comment] 2020-05-02 21:56
[tracing.log.bz2.txt](https://github.com/aristocratos/bashtop/files/4569102/tracing.log.bz2.txt)
added .txt to the end of the file name cause github complained it doesn't support bz2 xD

**Comment by drazil100** [comment] 2020-05-02 22:02
By the way if you like I can try to get another debug of it freezing and then resuming it rather than killing it in a frozen state. Not sure if that would be useful to you.

**Comment by aristocratos** [comment] 2020-05-02 22:03
That would be great!

In the current log time is consistent through the whole log, so unless you managed to kill it on the exact millisecond `read -rsd '' -t 0.001 -n 1 key` is executing, thats likely to be where it stalled. But another log would be great to verify.

**Comment by drazil100** [comment] 2020-05-02 22:27
![Screenshot from 2020-05-02 17-18-53](https://user-images.githubusercontent.com/17794391/80893654-fcf4ad80-8c99-11ea-8b25-4e94256ac28e.png)
Picture of it frozen.
copy of the log while it was frozen.
[tracing2-frozen.log.bz2.txt](https://github.com/aristocratos/bashtop/files/4569219/tracing2-frozen.log.bz2.txt)
copy of the log after pressing keys to make it resume and exiting it with the q key
[tracing2-unfrozen.log.bz2.txt](https://github.com/aristocratos/bashtop/files/4569220/tracing2-unfrozen.log.bz2.txt)

**Comment by drazil100** [comment] 2020-05-02 22:30
![Screenshot from 2020-05-02 17-18-53](https://user-images.githubusercontent.com/17794391/80893728-902de300-8c9a-11ea-8ce1-b4853d00396d.png)
uploaded the wrong image before the image in THIS post which I had uploaded before is a screenshot after I unfroze it before pressing q

**Comment by aristocratos** [comment] 2020-05-02 22:38
Nice work!
It's definitively `read -rsd '' -t 0.001 -n 1 key` that's stalling. But the question is why, and why only sometimes. That command gets called around 10 times minimum every update. Since it's only reading terminal input and should time out in 0.001 seconds...

**Comment by aristocratos** [comment] 2020-05-02 22:46
Gonna change around the error redirect for that command, it really shouldn't be able to interfere but can't really think of anything else to try.
Will be pushing a new version with some new features too in a few minutes.

**Comment by drazil100** [comment] 2020-05-02 22:48
Want me to test the new version when it comes out with --debug? If so let me know when you push the update.

**Comment by aristocratos** [comment] 2020-05-02 23:07
Pushed v0.8.22
Feel free to do some debugging if it's still stalling.
Gotta get some sleep, so will take a look at again tomorrow.

**Comment by drazil100** [comment] 2020-05-02 23:07
My friend just suggested something that may be worth trying. You could try putting keyboard input in its own thread and not worry about trying to time it out.

You mention in #36 why you don't put processing in its own thread but maybe input would work?

**Comment by aristocratos** [comment] 2020-05-02 23:17
Sadly won't work since read needs to be running in main script, wouldn't get any input running from a subprocess. And even if it did, it wouldn't be able to communicate with the main process directly.

**Comment by aristocratos** [comment] 2020-05-02 23:18
I tried experimenting with something along those lines with bash coproc, but just became a mess and very buggy.

**Comment by drazil100** [comment] 2020-05-03 02:33
Finally got around to testing it again and it still freezes on the read.

**Comment by magesticmage** [comment] 2020-05-03 08:29
Decided to try Ubuntu 20.04 in a VM and it still froze after a while...

**Comment by aristocratos** [comment] 2020-05-03 09:51
The problem with running process collection in background is that since a subprocess can't change the variables in the parent process, everything has to be written to disk. And in this case would be 1 big file and up to 100 smaller files, that then has to be read in to main script and assigned to the correct variables again, every update. And during disk read we can't get any input from keyboard at all, so the end result is more cpu usage, a lot of disk io operations and likely not much improvement in script responsiveness.
And it's still quiet possible the script would stall on that read command even with a higher timeout.

Btw, you have no errors in your error.log right?

The read command might be stalled if a trap is triggered, but the only traps I have setup are for window resize, ctrl-z, ctrl-c and errors.

Would you mind changing line 3356:
``` bash
IFS= read -rsd '' -t ${wait_time:-0.001} -n 1 key 2>/dev/null ||true
```
to:
``` bash
IFS= read -rsd '' -t ${wait_time:-0.001} -n 1 ||true
```
And see if you get anything in the regular error.log when it unfreezes.

**Comment by magesticmage** [comment] 2020-05-03 10:27
yeah no errors.

I changed line 3356 and re-ran bashtop, when it froze I hit a key to get it going again.

after doing this there are now some errors in the log:

New instance of bashtop version: 0.8.22 Pid: 28716
./bashtop: line 3356: read: error setting terminal attributes: Interrupted system call
./bashtop: line 3356: read: error setting terminal attributes: Interrupted system call
./bashtop: line 3356: read: error setting terminal attributes: Interrupted system call

**Comment by aristocratos** [comment] 2020-05-03 10:43
Ok, that error in itself shouldn't halt the read command, at least haven't done that on any of my test systems. 
Could you try changing the line to:
``` bash
IFS= read -rsd '' -t ${wait_time:-0.001} -n 1 < /dev/stdin ||true
```
And see if that makes any difference.

**Comment by drazil100** [comment] 2020-05-03 10:48
I got the same thing to the previous test request. Gonna try the new line now.

**Comment by drazil100** [comment] 2020-05-03 11:08
Ran it for a bit and at least didn't freeze but I was unable to input anything to the program. I can test more things when I wake up tomorrow though.

**Comment by aristocratos** [comment] 2020-05-03 12:14
Can't find a way to completely eliminate the possibility of it stalling, but will remove the call to the read command when iterating all processes, should reduce the likelihood of it happening very drastically. But will increase input lag a little bit on slower machines during updates.

It seems to depend a lot on overall cpu power, that's very likely why I haven't experienced the problem myself on my test machines with i7's. I increased the timeout to 0.000001 and could replicate the issue.

**Comment by aristocratos** [comment] 2020-05-03 13:30
Added changes in v0.8.23
Will hopefully make this a non issue.

**Comment by Generator** [comment] 2020-05-03 22:15
Freeze still present on v0.8.23
![Captura de ecrã_2020-05-03_23-12-27](https://user-images.githubusercontent.com/44146/80927182-d74bcf00-8d93-11ea-8552-1e1b322e393e.png)

**Comment by drazil100** [comment] 2020-05-03 22:16
> The problem with running process collection in background is that since a subprocess can't change the variables in the parent process, everything has to be written to disk. And in this case would be 1 big file and up to 100 smaller files, that then has to be read in to main script and assigned to the correct variables again, every update. And during disk read we can't get any input from keyboard at all, so the end result is more cpu usage, a lot of disk io operations and likely not much improvement in script responsiveness.

Now that I am more awake and am able to process this response better...

The proposed idea from my friend is to write **only input** to the disk and put literally everything else exactly as is in the background with the only difference being replacing read commands with checks to the input buffer file your main process generates. If you did it this way you would only have 1 file and that file wouldn't even have to exist if there is no input to process.

Actually now that im thinking about it... Another benefit to this would be that you wouldn't have to wait for the next read command for each key either. If the input is on its own thread you could process multiple keys on one read cycle. (though it would be up to you on how to handle this and not lock up the rest of the program)

**Comment by Generator** [comment] 2020-05-03 22:40
Tracing log from another freeze
[tracing.log.gz](https://github.com/aristocratos/bashtop/files/4572091/tracing.log.gz)

**Comment by magesticmage** [comment] 2020-05-04 02:19
tried v0.8.23, froze after about 10 min.
made a change:
found IFS= read -rsd '' -t ${wait_time:-0.001} -n 1 key 2>/dev/null ||true
replaced to 
IFS= read -rsd '' -t ${wait_time:-0.001} -n 1 < /dev/stdin ||true

made it to about 40 min before froze, nothing in the error log.

getting better

i have an CPU: Intel i5-4590 (4) @ 3.700GHz

**Comment by aristocratos** [comment] 2020-05-04 10:53
@drazil100 

> The proposed idea from my friend is to write only input to the disk and put literally everything else exactly as is in the background...

There is were bash runs into problems, since we can't put reading input into background and if the data collection is put to background all that data is lost unless written to disk. Since the subprocess inherits the variables from main process but any changes to the variables is lost to the main process.

**Comment by aristocratos** [comment] 2020-05-04 10:56
I'm gonna play around with the timeout times when I get some "time" over :)

Hopefully I can find a solution to this without increasing the input lag to annoying levels.

**Comment by aristocratos** [comment] 2020-05-04 10:58
If anyone know of good alternatives of using `read` to get keyboard input with a timeout that would help a lot.

**Comment by drazil100** [comment] 2020-05-04 12:06
> if the data collection is put to background all that data is lost unless written to disk. 

I think we are still not on the same page. The proposed idea is to NOT get the data collection back to the main thread. The idea is to have the background thread collect data AND display it and to use the main thread to exclusively read input and write it somewhere the background thread can access it. 

Also I’m not gonna push the idea if you think it’s a bad idea. I just want to make sure the idea is understood before it is dismissed.

**Comment by aristocratos** [comment] 2020-05-04 16:59
I think I finally solved it :D 

Have replaced the read command with `dd`, the downside is that the update cycle might not be as exact because I'm using stty to set the timeout, which is limited to tenths of a second instead of milliseconds. But shouldn't be too noticeable.

The new command:
```bash
key=$(stty -cooked min 0 time ${wait_time:-0}; dd bs=1 count=1 2>/dev/null)
```
But won't work if you just change it out, needs new time calculations, will push a new version in a little while.

**Comment by aristocratos** [comment] 2020-05-04 17:38
Pushed v0.8.24

Should finally be fixed!

**Comment by aristocratos** [comment] 2020-05-04 20:03
I will let this issue stay open until we have multiple confirms that it's fixed.

**Comment by aristocratos** [comment] 2020-05-04 20:32
> I think we are still not on the same page.

No I get what you mean. But I'm not sure how feasible it is without rewriting large chunks, there would still need to be a lot of data sent between the foreground and the background, it could surely be done by interrupting the background process with traps to read commands from foreground, or by running with coproc. But I'm pretty sure it would have a negative impact on both cpu and memory usage.

**Comment by magesticmage** [comment] 2020-05-05 02:18
been running the latest version for nearly 2 hours without a freeze, will leave it overnight and report back

**Comment by drazil100** [comment] 2020-05-05 02:21
I have also not had issues either. I think we got it.

**Comment by Generator** [comment] 2020-05-05 13:00
Same here, after two hours no issues freezing

**Comment by aristocratos** [comment] 2020-05-05 14:57
Great. Closing this for now. Reopen if problem persists.

**Closed by aristocratos** 2020-05-05 14:57 UTC
Labels: bug

**Comment by magesticmage** [comment] 2020-05-05 21:43
no issues after more than 18 hours
