### ISSUE TITLE
[REQUEST] Missing temperature important for overclocking

### ISSUE THREAD

**Issue by BullShark** [aristocratos/bashtop#118] opened 2020-05-20 05:34 UTC
**Is your feature request related to a problem? Please describe.**

I used nvidia coolbits in Linux to overclock my GPU and my bios to overclock my cpu also with an option passed to grub at boot, so temperatures are important to me.

**Describe the solution you'd like**

Under Core0, Core1, Core2, Core3 should be GPU0 with temperature output from this command.

$ nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader,nounits
43

I can't get a gpu usage percentage from nvidia-smi output. Run it with no arguments for more output. But if the output is parsed, the memory percentage can be obtained like this. Done in python, and bc might be needed for floating point division in bash.

```
totalMem = 4034
usedMem = 659
num = totalMem / 100
percentage = usedMem / num
print(percentage)
16.33614278631631
round(percentage, 1)
16.3
```

That percentage can also be used to generate a graph to match the ones for Core# above it (smaller ones, not the big one to the left).

**Describe alternatives you've considered**

I've considered conky for this or modifying a widget in kde since I already use kde widgets for other system stats.

**Additional context**

The memory usage isn't as important as having the temperature. gotop displays many temperatures but fails to get the gpu temperature, and I didn't like it as much as bashtop.

**Comment by aristocratos** [comment] 2020-05-20 22:02
Duplicate of #26
Currently focusing on OSX compatibility, so will still be a while before I get to this.

**Closed by aristocratos** 2020-05-20 22:02 UTC
Labels: duplicate
